import fs from "node:fs/promises"
import path from "node:path"
import { ApiError, withApiErrors } from "@/lib/auth"
import { requireBlogAdmin } from "@/lib/blog/access"
import { assertObjectId } from "@/lib/blog/mutations"
import { BlogMedia } from "@/lib/models/BlogMedia"

export const DELETE = withApiErrors(async (request, { params }) => {
  const { id } = await params
  await requireBlogAdmin(request, "blog.delete")
  assertObjectId(id)
  const media = await BlogMedia.findByIdAndDelete(id)
  if (!media) throw new ApiError(404, "Not found")
  // Only ever a bare filename inside public/uploads (the URL was generated by
  // the upload route), so this can't reach outside that folder.
  const name = media.url.replace(/^\/uploads\//, "")
  if (/^[A-Za-z0-9._-]+$/.test(name)) {
    await fs.unlink(path.join(process.cwd(), "public", "uploads", name)).catch(() => {})
  }
  return new Response(null, { status: 204 })
})
